site_name: My Docs
plugins:
  - search
  - codeinclude
theme:
  name: 'material'
markdown_extensions:
  - codehilite:
      linenums: False
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets